# Generated by Django 4.2.30 on 2026-08-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GADC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='details',
            field=models.TextField(max_length=500),
        ),
    ]
